- unit.go
- unit_test.go
a call to UnitService will currently panic if the unitname provided is invalid. This is simple to avoid by checking IsValidUnit before the call. However this causes problems if the value could be changed in between the calls. And practically speaking there are a number of places where UnitService is called and "IsValidUnit" isn't called.
Regardless of the above I still feel it's better for the library to return an error rather than panicing. It does mean an api change, but I think it's worth it.
> unitservice return err, not panic

- storage.go
- storage_test.go
- tag.go
- tag_test.go
A new kind of tag is added for referring to storage instances;
these are instances of charm storage. The format is "storage/N",
where "storage" is the name defined in charm storage metadata
and "N" is a unique sequence number.
> names: add StorageTag

- storage.go
- storage_test.go
This is similar to UnitService; it returns the
storage name from a storage instance ID.
> Add "StorageName" function

- tag.go
- tag_test.go
ReadableString will return a string that is appropriate for displaying
in the UI.  This is in response to review comments for review request
814: http://reviews.vapour.ws/r/814/
> Add ReadableString to generate a human-readable string from a tag

- filesystem.go
- filesystem_test.go
- tag.go
- tag_test.go
Add support for a Filesystem tag.
For maximum flexibility, the tag id is allowed to be any valid directory name. This is because in Juju, when no location is specified when creating a fs mount, the mount point is created from the tag id.
> Add FilesystemTag

- network.go
- network_test.go
Changes the accepted format for juju network names and tags to match the
charset accepted by MAAS: [\w_]+, taking into account in python, the
regexp package translates "\w" to "[a-zA-Z0-9-]".
See http://pad.lv/1446608.
(Review request: http://reviews.vapour.ws/r/1501/)
> Fixes lp:1446608 - accept [a-zA-Z0-9_-]+ in network names.

- subnet.go
- subnet_test.go
- tag.go
- tag_test.go
Subnet tags have the format "subnet-<CIDR>", where CIDR is a valid IPv4
or IPv6 CIDR, accepted by net.ParseCIDR() and having a matching
*net.IPNet.String() value after parsing. For example,
"subnet-10.20.30.40/16" is not valid, as it needs to be written as
"subnet-10.20.0.0/16".
(Review request: http://reviews.vapour.ws/r/2049/)
> Added subnet tag kind

- equality_test.go
- user.go
- user_test.go
We rename Provider to Domain because IsValidProvider overlaps uncomfortably with the "environment provider" terminology elsewhere in the Juju lexicon, and "domain" seems like the right term here.
We also rename the Username method to Canonical because that's really what it does, and having a Username method that returns a string that doesn't satisfy IsValidUserName seems counterintuitive at best.
(Review request: http://reviews.vapour.ws/r/2865/)
> add a UserTag.WithDomain method to allow us to alter the domain associated with a user

- user.go
- user_test.go
We lose the concept of "local" as a special name, leading to a much
simpler invariant - a username is external if and only if it has an "@" suffix.
The local domain is intuitively represented by the empty string.
This means that there is no need for the Canonical method, as users
are always in canonical form, and it also means that users as stored
currently in the juju state are already in canonical form as local users,
so there will be no need for a migration when we add information about
external users to the user database.
(Review request: http://reviews.vapour.ws/r/2867/)
> simpler user invariant: username has "@" => username is not local

- environ.go
- model.go
- model_test.go
- tag.go
- tag_test.go
Add new model tag.
A v2 API change will be required to remove the deprecated environment tag.
(Review request: http://reviews.vapour.ws/r/3604/)
> Add new model tag

- payload.go
- payload_test.go
- tag.go
Juju was using an unrelated UUID to identify payloads.  Doing so proved unnecessary.  This patch aligns with upcoming changes in core.  It updates the payload tag to support identifying payloads by their class name.
(Review request: http://reviews.vapour.ws/r/4875/)
> Use the payload class name as the ID.

- cloud.go
- cloud_test.go
- tag.go
- tag_test.go
Add a tag kind for identifying clouds. This will
be used in the Juju API when querying cloud details,
and querying/updating cloud credentials.
(Review request: http://reviews.vapour.ws/r/5146/)
> names: add "cloud" tag kind

- charm.go
- cloudcredential.go
- cloudcredential_test.go
- tag.go
- tag_test.go
- user.go
We add a new tag for identifying cloud credentials
within a Juju controller. A credential tag has three
components: the credential name, its owner (a valid
user), and the cloud to which the credential pertains.
(Review request: http://reviews.vapour.ws/r/5437/)
> Add CloudCredentialTag

- cloudcredential.go
- cloudcredential_test.go
Add a method to CloudCredential to return the
canonical form of a cloud credential ID. This
is due to the inclusion of user IDs, which have
canonical and non-canonical forms.
(Review request: http://reviews.vapour.ws/r/5441/)
> Add CloudCredential.Canonical method

- cloudcredential.go
- cloudcredential_test.go
- tag_test.go
We cannot use "-" to separate the
tag components for cloud credential
tags, as both clouds and credentials
may contain hyphens. Instead, we use
underscores.
(Review request: http://reviews.vapour.ws/r/5446/)
> Fix cloud credential tag encoding

- cloudcredential.go
- cloudcredential_test.go
- tag.go
- tag_test.go
Credential names now may contain @ and _ characters.
Since _ is used as a separator in the tag string, any names containing _ need to be quoted.
> Credential names now support @ and _

- charm.go
- charm_test.go
Previously charm urls needed to have the format:
`cs:~user/series/name-revision`
Now they can also have the format:
`cs:user/name/series/revision`
The old form is still accepted for backwards compatibility reasons.
Part of http://pad.lv/1584193
> Allow V3 charm urls in tags

- cloudcredential.go
- cloudcredential_test.go
- equality_test.go
- tag_test.go
- user.go
- user_test.go
Local users either have an empty domain or a "@local" domain. In either case, the user Id() will now simply be the user name (with no domain suffix). This means that the Canonical() method is no longer required.
> Only external users require a domain

- cloudcredential.go
- cloudcredential_test.go
Various pieces of code explicitly check for an empty cloud credential
and use an empty string for the tag if so.
This PR makes that behaviour easier to obtain.
> make CloudCredential Id and String work better on empty cloud credentials

- machine.go
- machine_test.go
The names package already knows if something is a container, so why not have a machine tag able to return the Parent.
> Be able to get the parent machine from a container machine tag.

- machine.go
- machine_test.go
The machine tag knows about container types and the number of the container, so add methods to return these from the tag.
> Add ChildId and ContainerType to MachineTag

- unit.go
- unit_test.go
In order to be able to infer application sequence numbers when not provided, the tag can now return the unit number.
> Be able to get unit number out of a UnitTag.

- unit.go
- unit_test.go
New function NewShortenedUnitTag - create a unit tag which has at most maxLength byte in String() representation, to use e.g. as a service name for systemd.
> NewShortenedUnitTag

- set.go
- set_test.go
As part of the change, we now have names.Set and names.NewSet, rather than the old set.Tags and set.NewTags.
> Add the set type from utils/set.

- filesystem.go
- filesystem_test.go
- tag.go
- unit.go
- unit_test.go
- volume.go
- volume_test.go
Filesystems and volumes can now be associated with units as well as machines.
As a driveby, fix some tests and add a couple more for unit tags.
> Filesystems and volumes can be attached to units

- subnet.go
- subnet_test.go
- tag_test.go
A CIDR is not a unique identifier of a subnet for juju any longer.  Changing the SubnetTag to be an ID rather than a CIDR.  Use names.v2 for a SubnetTag as a CIDR if required.
> SubnetTag is now an ID, not a CIDR.

- action.go
- action_test.go
- equality_test.go
- tag_test.go
For actions v2, we will transition to user friendly IDs; not a UUID but `<appname>-N`.
This PR adds support for making action tags with the new id format.
> Allow action ids to be <appname>-N

- action.go
- action_test.go
- equality_test.go
- tag_test.go
For actions v2, we've decided to use numbers as the tag id, rather than `<actionname-N>`.
> Action tags v2 are now numbers

- Gopkg.lock
- Gopkg.toml
This change relaxes the constraint for juju/version which currently prevents us from bringing this juju/errors version into juju.
> Bump juju/errors version

- application.go
- application_test.go
- tag.go
The names package is a great way to check if a name is valid, but really
struggles to tell you why a given name is valid. The following change
starts to do that by exposing a ValidateApplicationName, which will tell
you why a given name is wrong.
The code is rather dull, but is effective in that we try and be helpful
upfront (uppercase issues or numbers after the last hyphen), then just
point out an issue in a more programtic sense. Whilst the last is great
if you're a programmer, it's more cryptic for general users.
> Granular validation errors

- cloud.go
We are missing a lot of documentation around tag getters. This commit adds better docs for Cloud to support pkg.go.dev.
> Adding missing CloudTag docs.

- space.go
- space_test.go
- subnet.go
- subnet_test.go
- tag.go
A bug has been discovered recently in Juju 4.0 where we cannot move spaces because the subnet (which is automatically retrieved and inserted into the db with a new UUID v7 as primary key) cannot be passed as a new Subnet tag and therefore it panics.
The fix is to add a new validation regex for spaces and subnets which validate UUIDs v7 and keep the legacy (and deprecated) sequence ID as fallback validation for backward compatibility.
Run unit tests:
```
$ go test .
```
Also test the changes within Juju:
1) Add the replace statement on Juju's go.mod to point to this unmerged version locally (replace with your path):
```
replace github.com/juju/names/v6 => /home/nicolas/workspace/canonical/names
```
2) `make go-install` Juju
3) Actual QA:
```
$ juju bootstrap lxd c --build-agent
$ juju …
```
> feat: support UUID v7 tags for spaces and subnets

- space.go
- space_test.go
- subnet.go
- subnet_test.go
- tag_test.go
In a previous patch, the validation against UUIDs v7 was added for subnets and spaces. It turns out it wasn't needed for spaces since we use the space *name* as a tag in Juju.
This wrong validation was removed and the test was updated to reflect that we use a space name instead of a sequence number.
Also, the fallback validation for sequence numbers in subnets was removed since only uuid-subnets are used in juju 4.0.
```
$ go test .
```
Also test the changes within Juju:
1) Add the replace statement on Juju's go.mod to point to this unmerged version locally (replace with your path):
```
replace github.com/juju/names/v6 => /home/nicolas/workspace/canonical/names
```
2) `make go-install` Juju
3) Actual QA:
```
$ juju bootstrap lxd c --build-agent
$ juju add-model m
$ juju add-space beta
$ …
```
> fix: space/subnet tag shouldn't validate against UUIDs
