juju/names

space.go
space_test.go
tag.go
tag_test.go

(Review request: http://reviews.vapour.ws/r/1253/)

Added space tag.

---

LICENSE

(Review request: http://reviews.vapour.ws/r/1271/)

lp1435974 - Modify LICENSE to include copyright (juju/names)

---

LICENSE

(Review request: http://reviews.vapour.ws/r/1316/)

LGPL v3 License (juju/names master)

---

LICENSE

(Review request: http://reviews.vapour.ws/r/1315/)

LGPL v3 License (juju/names 1.22)

---

LICENSE

(Review request: http://reviews.vapour.ws/r/1342/)

LGPL v3 License (juju/names 1.23)

---

ipaddress.go
ipaddress_test.go
space.go
tag.go
tag_test.go

(Review request: http://reviews.vapour.ws/r/1972/)

Added IP address tag kind.

---

user.go
user_test.go

This is too controversial, so we revert the changes.
(Review request: http://reviews.vapour.ws/r/2897/)

revert PR #56

---

action.go
action_test.go

What the title says. Not a lot to see here, but this is needed for some upcoming PR's in core
(Review request: http://reviews.vapour.ws/r/4024/)

actions: make machines action receivers

---

action.go
action_test.go

(Review request: http://reviews.vapour.ws/r/4350/)

Added actionreceiver from tag function

---

model.go
model_test.go

Part of fix for lp#1568944
This is a v2 commit for what is also in https://github.com/juju/names/pull/66
(Review request: http://reviews.vapour.ws/r/4956/)

Add IsValidModelName v2

---

model.go
model_test.go

Part of fix for lp#1568944 and required for https://github.com/juju/juju/pull/5470
(Review request: http://reviews.vapour.ws/r/4925/)

Add IsValidModelName

---

controller.go
controller_test.go
model_test.go
tag.go

Add a controller tag 
(Review request: http://reviews.vapour.ws/r/5259/)

Add controller tag.

---

unit.go
unit_test.go

(Review request: http://reviews.vapour.ws/r/4850/)

unit: Added a non panicing version of NewUnitTag called NewUnitTagFromName

---

charm.go
charm_test.go

Review changes that I thought I'd pushed - gah! Luckily they're just comment clarifications.

Clarify comments about V1/V3 tag formats

---

controlleragent.go
controlleragent_test.go
tag.go
tag_test.go

Add a new tag for controller agents.

Add new controller agent tag

---

controlleragent.go
controlleragent_test.go
tag.go
tag_test.go

Pass in controller id as a string not an int.

controller agent id is a string

---

Gopkg.lock
Gopkg.toml

using names.v3 as a dependency in juju/juju, deps was unhappy without revisions specified.

use revisions not branch

---

unit.go
unit_test.go

Rather than copying a unitNum function to a third place.

Added names.UnitNumber

---

Gopkg.lock
Gopkg.toml

Need to update juju/juju dependencies for juju/utils.

Update dependencies for juju/utils.

---

operation.go
operation_test.go
tag.go
tag_test.go

Add support for an operation tag.

Add new operation tag

---

Gopkg.lock
Gopkg.toml

Use latest juju/utils commit to hopefully solve juju dep issue.

Update juju/utils dependency

---

Makefile
model.go
model_test.go

Add ModelTag.ShortId() method;
Derive by: add a `check` target to fix the `github-check-merge-juju-names` job;

Add ModelTag.ShortId() method;
